// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MediaAlbumService is an autogenerated mock type for the mediaAlbumService type
type MediaAlbumService struct {
	mock.Mock
}

type MediaAlbumService_Expecter struct {
	mock *mock.Mock
}

func (_m *MediaAlbumService) EXPECT() *MediaAlbumService_Expecter {
	return &MediaAlbumService_Expecter{mock: &_m.Mock}
}

// NewMediaAlbumService creates a new instance of MediaAlbumService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMediaAlbumService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MediaAlbumService {
	mock := &MediaAlbumService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
