// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: transport/grpc/pb/telegram.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_pb_telegram_proto_rawDescGZIP(), []int{0}
}

type ClientDoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Done          bool                   `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDoneResponse) Reset() {
	*x = ClientDoneResponse{}
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDoneResponse) ProtoMessage() {}

func (x *ClientDoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDoneResponse.ProtoReflect.Descriptor instead.
func (*ClientDoneResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_pb_telegram_proto_rawDescGZIP(), []int{1}
}

func (x *ClientDoneResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChatId        int64                  `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_transport_grpc_pb_telegram_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Message) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MessageIds    []int64                `protobuf:"varint,2,rep,packed,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_pb_telegram_proto_rawDescGZIP(), []int{3}
}

func (x *GetMessagesRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *GetMessagesRequest) GetMessageIds() []int64 {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

type GetLastMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastMessageRequest) Reset() {
	*x = GetLastMessageRequest{}
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastMessageRequest) ProtoMessage() {}

func (x *GetLastMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastMessageRequest.ProtoReflect.Descriptor instead.
func (*GetLastMessageRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_pb_telegram_proto_rawDescGZIP(), []int{4}
}

func (x *GetLastMessageRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_pb_telegram_proto_rawDescGZIP(), []int{5}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type CreateMessageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChatId           int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Text             string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	ReplyToMessageId int64                  `protobuf:"varint,3,opt,name=reply_to_message_id,json=replyToMessageId,proto3" json:"reply_to_message_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateMessageRequest) Reset() {
	*x = CreateMessageRequest{}
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageRequest) ProtoMessage() {}

func (x *CreateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_pb_telegram_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMessageRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *CreateMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreateMessageRequest) GetReplyToMessageId() int64 {
	if x != nil {
		return x.ReplyToMessageId
	}
	return 0
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_pb_telegram_proto_rawDescGZIP(), []int{7}
}

func (x *MessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type GetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_pb_telegram_proto_rawDescGZIP(), []int{8}
}

func (x *GetMessageRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *GetMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type UpdateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageRequest) Reset() {
	*x = UpdateMessageRequest{}
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageRequest) ProtoMessage() {}

func (x *UpdateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageRequest.ProtoReflect.Descriptor instead.
func (*UpdateMessageRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_pb_telegram_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMessageRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *UpdateMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *UpdateMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DeleteMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MessageIds    []int64                `protobuf:"varint,2,rep,packed,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessagesRequest) Reset() {
	*x = DeleteMessagesRequest{}
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessagesRequest) ProtoMessage() {}

func (x *DeleteMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessagesRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessagesRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_pb_telegram_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMessagesRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *DeleteMessagesRequest) GetMessageIds() []int64 {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

type DeleteMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessagesResponse) Reset() {
	*x = DeleteMessagesResponse{}
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessagesResponse) ProtoMessage() {}

func (x *DeleteMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_pb_telegram_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessagesResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessagesResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_pb_telegram_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteMessagesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_transport_grpc_pb_telegram_proto protoreflect.FileDescriptor

const file_transport_grpc_pb_telegram_proto_rawDesc = "" +
	"\n" +
	" transport/grpc/pb/telegram.proto\x12\x02pb\"\x0e\n" +
	"\fEmptyRequest\"(\n" +
	"\x12ClientDoneResponse\x12\x12\n" +
	"\x04done\x18\x01 \x01(\bR\x04done\"U\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\x03R\x06chatId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"N\n" +
	"\x12GetMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x1f\n" +
	"\vmessage_ids\x18\x02 \x03(\x03R\n" +
	"messageIds\"0\n" +
	"\x15GetLastMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\">\n" +
	"\x13GetMessagesResponse\x12'\n" +
	"\bmessages\x18\x01 \x03(\v2\v.pb.MessageR\bmessages\"r\n" +
	"\x14CreateMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12-\n" +
	"\x13reply_to_message_id\x18\x03 \x01(\x03R\x10replyToMessageId\"8\n" +
	"\x0fMessageResponse\x12%\n" +
	"\amessage\x18\x01 \x01(\v2\v.pb.MessageR\amessage\"K\n" +
	"\x11GetMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\"b\n" +
	"\x14UpdateMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"Q\n" +
	"\x15DeleteMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x1f\n" +
	"\vmessage_ids\x18\x02 \x03(\x03R\n" +
	"messageIds\"2\n" +
	"\x16DeleteMessagesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xcc\x03\n" +
	"\n" +
	"FacadeGRPC\x129\n" +
	"\rGetClientDone\x12\x10.pb.EmptyRequest\x1a\x16.pb.ClientDoneResponse\x12>\n" +
	"\vGetMessages\x12\x16.pb.GetMessagesRequest\x1a\x17.pb.GetMessagesResponse\x12@\n" +
	"\x0eGetLastMessage\x12\x19.pb.GetLastMessageRequest\x1a\x13.pb.MessageResponse\x12>\n" +
	"\rCreateMessage\x12\x18.pb.CreateMessageRequest\x1a\x13.pb.MessageResponse\x128\n" +
	"\n" +
	"GetMessage\x12\x15.pb.GetMessageRequest\x1a\x13.pb.MessageResponse\x12>\n" +
	"\rUpdateMessage\x12\x18.pb.UpdateMessageRequest\x1a\x13.pb.MessageResponse\x12G\n" +
	"\x0eDeleteMessages\x12\x19.pb.DeleteMessagesRequest\x1a\x1a.pb.DeleteMessagesResponseB-Z+github.com/comerc/budva43/transport/grpc/pbb\x06proto3"

var (
	file_transport_grpc_pb_telegram_proto_rawDescOnce sync.Once
	file_transport_grpc_pb_telegram_proto_rawDescData []byte
)

func file_transport_grpc_pb_telegram_proto_rawDescGZIP() []byte {
	file_transport_grpc_pb_telegram_proto_rawDescOnce.Do(func() {
		file_transport_grpc_pb_telegram_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_grpc_pb_telegram_proto_rawDesc), len(file_transport_grpc_pb_telegram_proto_rawDesc)))
	})
	return file_transport_grpc_pb_telegram_proto_rawDescData
}

var file_transport_grpc_pb_telegram_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_transport_grpc_pb_telegram_proto_goTypes = []any{
	(*EmptyRequest)(nil),           // 0: pb.EmptyRequest
	(*ClientDoneResponse)(nil),     // 1: pb.ClientDoneResponse
	(*Message)(nil),                // 2: pb.Message
	(*GetMessagesRequest)(nil),     // 3: pb.GetMessagesRequest
	(*GetLastMessageRequest)(nil),  // 4: pb.GetLastMessageRequest
	(*GetMessagesResponse)(nil),    // 5: pb.GetMessagesResponse
	(*CreateMessageRequest)(nil),   // 6: pb.CreateMessageRequest
	(*MessageResponse)(nil),        // 7: pb.MessageResponse
	(*GetMessageRequest)(nil),      // 8: pb.GetMessageRequest
	(*UpdateMessageRequest)(nil),   // 9: pb.UpdateMessageRequest
	(*DeleteMessagesRequest)(nil),  // 10: pb.DeleteMessagesRequest
	(*DeleteMessagesResponse)(nil), // 11: pb.DeleteMessagesResponse
}
var file_transport_grpc_pb_telegram_proto_depIdxs = []int32{
	2,  // 0: pb.GetMessagesResponse.messages:type_name -> pb.Message
	2,  // 1: pb.MessageResponse.message:type_name -> pb.Message
	0,  // 2: pb.FacadeGRPC.GetClientDone:input_type -> pb.EmptyRequest
	3,  // 3: pb.FacadeGRPC.GetMessages:input_type -> pb.GetMessagesRequest
	4,  // 4: pb.FacadeGRPC.GetLastMessage:input_type -> pb.GetLastMessageRequest
	6,  // 5: pb.FacadeGRPC.CreateMessage:input_type -> pb.CreateMessageRequest
	8,  // 6: pb.FacadeGRPC.GetMessage:input_type -> pb.GetMessageRequest
	9,  // 7: pb.FacadeGRPC.UpdateMessage:input_type -> pb.UpdateMessageRequest
	10, // 8: pb.FacadeGRPC.DeleteMessages:input_type -> pb.DeleteMessagesRequest
	1,  // 9: pb.FacadeGRPC.GetClientDone:output_type -> pb.ClientDoneResponse
	5,  // 10: pb.FacadeGRPC.GetMessages:output_type -> pb.GetMessagesResponse
	7,  // 11: pb.FacadeGRPC.GetLastMessage:output_type -> pb.MessageResponse
	7,  // 12: pb.FacadeGRPC.CreateMessage:output_type -> pb.MessageResponse
	7,  // 13: pb.FacadeGRPC.GetMessage:output_type -> pb.MessageResponse
	7,  // 14: pb.FacadeGRPC.UpdateMessage:output_type -> pb.MessageResponse
	11, // 15: pb.FacadeGRPC.DeleteMessages:output_type -> pb.DeleteMessagesResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_transport_grpc_pb_telegram_proto_init() }
func file_transport_grpc_pb_telegram_proto_init() {
	if File_transport_grpc_pb_telegram_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_grpc_pb_telegram_proto_rawDesc), len(file_transport_grpc_pb_telegram_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_grpc_pb_telegram_proto_goTypes,
		DependencyIndexes: file_transport_grpc_pb_telegram_proto_depIdxs,
		MessageInfos:      file_transport_grpc_pb_telegram_proto_msgTypes,
	}.Build()
	File_transport_grpc_pb_telegram_proto = out.File
	file_transport_grpc_pb_telegram_proto_goTypes = nil
	file_transport_grpc_pb_telegram_proto_depIdxs = nil
}
