// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StorageService is an autogenerated mock type for the storageService type
type StorageService struct {
	mock.Mock
}

type StorageService_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageService) EXPECT() *StorageService_Expecter {
	return &StorageService_Expecter{mock: &_m.Mock}
}

// DeleteAnswerMessageId provides a mock function with given fields: dstChatId, tmpMessageId
func (_m *StorageService) DeleteAnswerMessageId(dstChatId int64, tmpMessageId int64) {
	_m.Called(dstChatId, tmpMessageId)
}

// StorageService_DeleteAnswerMessageId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAnswerMessageId'
type StorageService_DeleteAnswerMessageId_Call struct {
	*mock.Call
}

// DeleteAnswerMessageId is a helper method to define mock.On call
//   - dstChatId int64
//   - tmpMessageId int64
func (_e *StorageService_Expecter) DeleteAnswerMessageId(dstChatId interface{}, tmpMessageId interface{}) *StorageService_DeleteAnswerMessageId_Call {
	return &StorageService_DeleteAnswerMessageId_Call{Call: _e.mock.On("DeleteAnswerMessageId", dstChatId, tmpMessageId)}
}

func (_c *StorageService_DeleteAnswerMessageId_Call) Run(run func(dstChatId int64, tmpMessageId int64)) *StorageService_DeleteAnswerMessageId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64))
	})
	return _c
}

func (_c *StorageService_DeleteAnswerMessageId_Call) Return() *StorageService_DeleteAnswerMessageId_Call {
	_c.Call.Return()
	return _c
}

func (_c *StorageService_DeleteAnswerMessageId_Call) RunAndReturn(run func(int64, int64)) *StorageService_DeleteAnswerMessageId_Call {
	_c.Run(run)
	return _c
}

// GetCopiedMessageIds provides a mock function with given fields: chatId, messageId
func (_m *StorageService) GetCopiedMessageIds(chatId int64, messageId int64) []string {
	ret := _m.Called(chatId, messageId)

	if len(ret) == 0 {
		panic("no return value specified for GetCopiedMessageIds")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(int64, int64) []string); ok {
		r0 = rf(chatId, messageId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// StorageService_GetCopiedMessageIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCopiedMessageIds'
type StorageService_GetCopiedMessageIds_Call struct {
	*mock.Call
}

// GetCopiedMessageIds is a helper method to define mock.On call
//   - chatId int64
//   - messageId int64
func (_e *StorageService_Expecter) GetCopiedMessageIds(chatId interface{}, messageId interface{}) *StorageService_GetCopiedMessageIds_Call {
	return &StorageService_GetCopiedMessageIds_Call{Call: _e.mock.On("GetCopiedMessageIds", chatId, messageId)}
}

func (_c *StorageService_GetCopiedMessageIds_Call) Run(run func(chatId int64, messageId int64)) *StorageService_GetCopiedMessageIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64))
	})
	return _c
}

func (_c *StorageService_GetCopiedMessageIds_Call) Return(_a0 []string) *StorageService_GetCopiedMessageIds_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageService_GetCopiedMessageIds_Call) RunAndReturn(run func(int64, int64) []string) *StorageService_GetCopiedMessageIds_Call {
	_c.Call.Return(run)
	return _c
}

// GetNewMessageId provides a mock function with given fields: chatId, tmpMessageId
func (_m *StorageService) GetNewMessageId(chatId int64, tmpMessageId int64) int64 {
	ret := _m.Called(chatId, tmpMessageId)

	if len(ret) == 0 {
		panic("no return value specified for GetNewMessageId")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func(int64, int64) int64); ok {
		r0 = rf(chatId, tmpMessageId)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// StorageService_GetNewMessageId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewMessageId'
type StorageService_GetNewMessageId_Call struct {
	*mock.Call
}

// GetNewMessageId is a helper method to define mock.On call
//   - chatId int64
//   - tmpMessageId int64
func (_e *StorageService_Expecter) GetNewMessageId(chatId interface{}, tmpMessageId interface{}) *StorageService_GetNewMessageId_Call {
	return &StorageService_GetNewMessageId_Call{Call: _e.mock.On("GetNewMessageId", chatId, tmpMessageId)}
}

func (_c *StorageService_GetNewMessageId_Call) Run(run func(chatId int64, tmpMessageId int64)) *StorageService_GetNewMessageId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64))
	})
	return _c
}

func (_c *StorageService_GetNewMessageId_Call) Return(_a0 int64) *StorageService_GetNewMessageId_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageService_GetNewMessageId_Call) RunAndReturn(run func(int64, int64) int64) *StorageService_GetNewMessageId_Call {
	_c.Call.Return(run)
	return _c
}

// SetAnswerMessageId provides a mock function with given fields: dstChatId, tmpMessageId, chatId, messageId
func (_m *StorageService) SetAnswerMessageId(dstChatId int64, tmpMessageId int64, chatId int64, messageId int64) {
	_m.Called(dstChatId, tmpMessageId, chatId, messageId)
}

// StorageService_SetAnswerMessageId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAnswerMessageId'
type StorageService_SetAnswerMessageId_Call struct {
	*mock.Call
}

// SetAnswerMessageId is a helper method to define mock.On call
//   - dstChatId int64
//   - tmpMessageId int64
//   - chatId int64
//   - messageId int64
func (_e *StorageService_Expecter) SetAnswerMessageId(dstChatId interface{}, tmpMessageId interface{}, chatId interface{}, messageId interface{}) *StorageService_SetAnswerMessageId_Call {
	return &StorageService_SetAnswerMessageId_Call{Call: _e.mock.On("SetAnswerMessageId", dstChatId, tmpMessageId, chatId, messageId)}
}

func (_c *StorageService_SetAnswerMessageId_Call) Run(run func(dstChatId int64, tmpMessageId int64, chatId int64, messageId int64)) *StorageService_SetAnswerMessageId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *StorageService_SetAnswerMessageId_Call) Return() *StorageService_SetAnswerMessageId_Call {
	_c.Call.Return()
	return _c
}

func (_c *StorageService_SetAnswerMessageId_Call) RunAndReturn(run func(int64, int64, int64, int64)) *StorageService_SetAnswerMessageId_Call {
	_c.Run(run)
	return _c
}

// NewStorageService creates a new instance of StorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageService {
	mock := &StorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
