// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	client "github.com/zelenin/go-tdlib/client"
)

// TelegramRepo is an autogenerated mock type for the telegramRepo type
type TelegramRepo struct {
	mock.Mock
}

type TelegramRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *TelegramRepo) EXPECT() *TelegramRepo_Expecter {
	return &TelegramRepo_Expecter{mock: &_m.Mock}
}

// EditMessageCaption provides a mock function with given fields: _a0
func (_m *TelegramRepo) EditMessageCaption(_a0 *client.EditMessageCaptionRequest) (*client.Message, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for EditMessageCaption")
	}

	var r0 *client.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(*client.EditMessageCaptionRequest) (*client.Message, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*client.EditMessageCaptionRequest) *client.Message); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(*client.EditMessageCaptionRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TelegramRepo_EditMessageCaption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditMessageCaption'
type TelegramRepo_EditMessageCaption_Call struct {
	*mock.Call
}

// EditMessageCaption is a helper method to define mock.On call
//   - _a0 *client.EditMessageCaptionRequest
func (_e *TelegramRepo_Expecter) EditMessageCaption(_a0 interface{}) *TelegramRepo_EditMessageCaption_Call {
	return &TelegramRepo_EditMessageCaption_Call{Call: _e.mock.On("EditMessageCaption", _a0)}
}

func (_c *TelegramRepo_EditMessageCaption_Call) Run(run func(_a0 *client.EditMessageCaptionRequest)) *TelegramRepo_EditMessageCaption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*client.EditMessageCaptionRequest))
	})
	return _c
}

func (_c *TelegramRepo_EditMessageCaption_Call) Return(_a0 *client.Message, _a1 error) *TelegramRepo_EditMessageCaption_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TelegramRepo_EditMessageCaption_Call) RunAndReturn(run func(*client.EditMessageCaptionRequest) (*client.Message, error)) *TelegramRepo_EditMessageCaption_Call {
	_c.Call.Return(run)
	return _c
}

// EditMessageText provides a mock function with given fields: _a0
func (_m *TelegramRepo) EditMessageText(_a0 *client.EditMessageTextRequest) (*client.Message, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for EditMessageText")
	}

	var r0 *client.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(*client.EditMessageTextRequest) (*client.Message, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*client.EditMessageTextRequest) *client.Message); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(*client.EditMessageTextRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TelegramRepo_EditMessageText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditMessageText'
type TelegramRepo_EditMessageText_Call struct {
	*mock.Call
}

// EditMessageText is a helper method to define mock.On call
//   - _a0 *client.EditMessageTextRequest
func (_e *TelegramRepo_Expecter) EditMessageText(_a0 interface{}) *TelegramRepo_EditMessageText_Call {
	return &TelegramRepo_EditMessageText_Call{Call: _e.mock.On("EditMessageText", _a0)}
}

func (_c *TelegramRepo_EditMessageText_Call) Run(run func(_a0 *client.EditMessageTextRequest)) *TelegramRepo_EditMessageText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*client.EditMessageTextRequest))
	})
	return _c
}

func (_c *TelegramRepo_EditMessageText_Call) Return(_a0 *client.Message, _a1 error) *TelegramRepo_EditMessageText_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TelegramRepo_EditMessageText_Call) RunAndReturn(run func(*client.EditMessageTextRequest) (*client.Message, error)) *TelegramRepo_EditMessageText_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessage provides a mock function with given fields: _a0
func (_m *TelegramRepo) GetMessage(_a0 *client.GetMessageRequest) (*client.Message, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetMessage")
	}

	var r0 *client.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(*client.GetMessageRequest) (*client.Message, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*client.GetMessageRequest) *client.Message); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(*client.GetMessageRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TelegramRepo_GetMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessage'
type TelegramRepo_GetMessage_Call struct {
	*mock.Call
}

// GetMessage is a helper method to define mock.On call
//   - _a0 *client.GetMessageRequest
func (_e *TelegramRepo_Expecter) GetMessage(_a0 interface{}) *TelegramRepo_GetMessage_Call {
	return &TelegramRepo_GetMessage_Call{Call: _e.mock.On("GetMessage", _a0)}
}

func (_c *TelegramRepo_GetMessage_Call) Run(run func(_a0 *client.GetMessageRequest)) *TelegramRepo_GetMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*client.GetMessageRequest))
	})
	return _c
}

func (_c *TelegramRepo_GetMessage_Call) Return(_a0 *client.Message, _a1 error) *TelegramRepo_GetMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TelegramRepo_GetMessage_Call) RunAndReturn(run func(*client.GetMessageRequest) (*client.Message, error)) *TelegramRepo_GetMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewTelegramRepo creates a new instance of TelegramRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelegramRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelegramRepo {
	mock := &TelegramRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
