version: "2"
run:
  modules-download-mode: readonly
  allow-parallel-runners: true
linters:
  enable:
    - bodyclose # checks that HTTP response body is closed
    - copyloopvar # reports loop variables that are copied
    - gosec # inspects source code for security problems
    - prealloc # reports slice declarations that could be preallocated
    - gocritic # the most opinionated Go source code linter
    - revive # drop-in replacement of golint
    - unconvert # detects unneeded conversions in if statements
  disable:
    - unused # отключение предупреждений о неиспользуемых функциях
  settings:
    gocritic:
      enabled-checks:
        - hugeParam
    revive:
      severity: error
      rules:
        - name: atomic # commonly mistaken usages of the sync/atomic package
        - name: bare-return # bare (a.k.a. naked) returns
        - name: comment-spacings # comment spacing
        - name: constant-logical-expr # logical expressions that evaluate always to the same value
        - name: context-as-argument #  should be the first parameter of a function
        - name: context-keys-type # basic types should not be used as a key in `context.WithValue`
        # - name: cyclomatic # cyclomatic complexity is a measure of code complexity          
        - name: datarace # potential dataraces caused
        - name: defer # some common mistakes when using defer statement
        - name: early-return # to avoid if-then-else constructions
        - name: error-return # the errors should be last in the list of returned values by a function
        - name: errorf # use `fmt.Errorf()` instead of `errors.New(fmt.Sprintf())`
        - name: filename-format # enforces conventions on source file names
          arguments: ["^[_a-z][_a-z0-9]*\\.go$"]
        - name: get-return # functions with names prefixed with Get are supposed to return a value
        - name: identical-branches # an if-then-else conditional with identical implementations in both branches is an error
        - name: if-return # checking if an error is nil to just after return the error or nil is redundant
        - name: import-alias-naming # enforces clear and lowercase import alias names, aliases with underscores ("_") are always allowed
          arguments: ["^[a-z][A-Za-z0-9]{0,}$"]
        - name: increment-decrement # spots expressions like `i += 1` and `i -= 1` and proposes to change them into `i++` and `i--`
        - name: indent-error-flow # highlights redundant else-blocks that can be eliminated from the code
        - name: modifies-parameter # a function modifies one or more of its parameters
        - name: modifies-value-receiver # a method modifies its receiver
        - name: range # suggests a shorter way of writing ranges that do not use the second value
        - name: receiver-naming # receiver names in a method should reflect their identity
        - name: redefines-builtin-id # redefining these built in names can lead to bugs very difficult to detect
        # - name: redundant-import-alias # alias used on the import statement matches the imported package name
        - name: string-of-int # `string(42)` is not `"42"`
        - name: time-equal # using `==` and `!=` for equality `check time.Time` is not correct, use `time.Equal()` instead
        # - name: unchecked-type-assertion # checks whether a type assertion result is checked (the ok value)
        - name: unconditional-recursion # detects and warns about unconditional (direct) recursive calls
        - name: unexported-return # an exported function or method returns a value of an un-exported type
        - name: unnecessary-stmt # redundant statements like a break at the end of a case block
        - name: unreachable-code # unreachable code
        # - name: unused-parameter # unused parameter in function parameters
        # - name: unused-receiver # unused-receiver
        - name: use-any # proposes to replace instances of `interface{}` with `any`
        - name: useless-break # a `break` statement is unnecessary in a switch-case statement
        - name: waitgroup-by-value # a `sync.WaitGroup` expected as a by-value parameter in a function or method
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*_mock.go$
      - mocks
      - testing
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci # enable custom order of sections 
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/comerc/budva43)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - .*_mock.go$
      - mocks
      - testing
      - third_party$
      - builtin$
      - examples$
