services:
  tdlib:
    build:
      dockerfile: Dockerfile
      context: ./pkg/tdlib
    image: tdlib:latest
  dev:
    build:
      dockerfile: Dockerfile
      context: .
    image: budva43/dev:latest
    depends_on:
      - tdlib
    command: sleep infinity
    volumes:
      - .:/workspaces/budva43:cached
    environment:
      CGO_CFLAGS: "-I/td/tdlib/include"
      CGO_LDFLAGS: "-Wl,-rpath,/td/tdlib/lib -L/td/tdlib/lib -ltdjson"
