services:
  tdlib-ubuntu:
    build:
      dockerfile: Dockerfile
      context: ./pkg/tdlib-ubuntu
    image: tdlib-ubuntu:latest
  dev:
    build:
      dockerfile: Dockerfile
      context: .
    image: budva43/dev:latest
    depends_on:
      - tdlib-ubuntu
    command: sleep infinity
    volumes:
      - .:/workspaces/budva43:cached
