server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: budva43-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: budva43
          service: app
          __path__: /var/log/app/app.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            module: module
            msg: msg
            time: time
      - labels:
          level:
          module:
      - timestamp:
          source: time
          format: RFC3339Nano

  - job_name: budva43-badger
    static_configs:
      - targets:
          - localhost
        labels:
          job: budva43
          service: badger
          __path__: /var/log/app/badger.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            time: time
      - labels:
          level:
      - timestamp:
          source: time
          format: RFC3339Nano

  - job_name: budva43-telegram
    static_configs:
      - targets:
          - localhost
        labels:
          job: budva43
          service: telegram
          __path__: /var/log/app/telegram.log
