// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StorageRepo is an autogenerated mock type for the storageRepo type
type StorageRepo struct {
	mock.Mock
}

type StorageRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageRepo) EXPECT() *StorageRepo_Expecter {
	return &StorageRepo_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: key
func (_m *StorageRepo) Delete(key string) error {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type StorageRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key string
func (_e *StorageRepo_Expecter) Delete(key interface{}) *StorageRepo_Delete_Call {
	return &StorageRepo_Delete_Call{Call: _e.mock.On("Delete", key)}
}

func (_c *StorageRepo_Delete_Call) Run(run func(key string)) *StorageRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *StorageRepo_Delete_Call) Return(_a0 error) *StorageRepo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageRepo_Delete_Call) RunAndReturn(run func(string) error) *StorageRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *StorageRepo) Get(key string) (string, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type StorageRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *StorageRepo_Expecter) Get(key interface{}) *StorageRepo_Get_Call {
	return &StorageRepo_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *StorageRepo_Get_Call) Run(run func(key string)) *StorageRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *StorageRepo_Get_Call) Return(_a0 string, _a1 error) *StorageRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageRepo_Get_Call) RunAndReturn(run func(string) (string, error)) *StorageRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetSet provides a mock function with given fields: key, fn
func (_m *StorageRepo) GetSet(key string, fn func(string) (string, error)) (string, error) {
	ret := _m.Called(key, fn)

	if len(ret) == 0 {
		panic("no return value specified for GetSet")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, func(string) (string, error)) (string, error)); ok {
		return rf(key, fn)
	}
	if rf, ok := ret.Get(0).(func(string, func(string) (string, error)) string); ok {
		r0 = rf(key, fn)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, func(string) (string, error)) error); ok {
		r1 = rf(key, fn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageRepo_GetSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSet'
type StorageRepo_GetSet_Call struct {
	*mock.Call
}

// GetSet is a helper method to define mock.On call
//   - key string
//   - fn func(string)(string , error)
func (_e *StorageRepo_Expecter) GetSet(key interface{}, fn interface{}) *StorageRepo_GetSet_Call {
	return &StorageRepo_GetSet_Call{Call: _e.mock.On("GetSet", key, fn)}
}

func (_c *StorageRepo_GetSet_Call) Run(run func(key string, fn func(string) (string, error))) *StorageRepo_GetSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(func(string) (string, error)))
	})
	return _c
}

func (_c *StorageRepo_GetSet_Call) Return(_a0 string, _a1 error) *StorageRepo_GetSet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageRepo_GetSet_Call) RunAndReturn(run func(string, func(string) (string, error)) (string, error)) *StorageRepo_GetSet_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function with given fields: key
func (_m *StorageRepo) Increment(key string) (uint64, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (uint64, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) uint64); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageRepo_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type StorageRepo_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - key string
func (_e *StorageRepo_Expecter) Increment(key interface{}) *StorageRepo_Increment_Call {
	return &StorageRepo_Increment_Call{Call: _e.mock.On("Increment", key)}
}

func (_c *StorageRepo_Increment_Call) Run(run func(key string)) *StorageRepo_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *StorageRepo_Increment_Call) Return(_a0 uint64, _a1 error) *StorageRepo_Increment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageRepo_Increment_Call) RunAndReturn(run func(string) (uint64, error)) *StorageRepo_Increment_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, value
func (_m *StorageRepo) Set(key string, value string) error {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageRepo_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type StorageRepo_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value string
func (_e *StorageRepo_Expecter) Set(key interface{}, value interface{}) *StorageRepo_Set_Call {
	return &StorageRepo_Set_Call{Call: _e.mock.On("Set", key, value)}
}

func (_c *StorageRepo_Set_Call) Run(run func(key string, value string)) *StorageRepo_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *StorageRepo_Set_Call) Return(_a0 error) *StorageRepo_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageRepo_Set_Call) RunAndReturn(run func(string, string) error) *StorageRepo_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageRepo creates a new instance of StorageRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageRepo {
	mock := &StorageRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
