// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ChatService is an autogenerated mock type for the chatService type
type ChatService struct {
	mock.Mock
}

type ChatService_Expecter struct {
	mock *mock.Mock
}

func (_m *ChatService) EXPECT() *ChatService_Expecter {
	return &ChatService_Expecter{mock: &_m.Mock}
}

// IsBasicGroup provides a mock function with given fields: chatId
func (_m *ChatService) IsBasicGroup(chatId int64) (bool, error) {
	ret := _m.Called(chatId)

	if len(ret) == 0 {
		panic("no return value specified for IsBasicGroup")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (bool, error)); ok {
		return rf(chatId)
	}
	if rf, ok := ret.Get(0).(func(int64) bool); ok {
		r0 = rf(chatId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(chatId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChatService_IsBasicGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBasicGroup'
type ChatService_IsBasicGroup_Call struct {
	*mock.Call
}

// IsBasicGroup is a helper method to define mock.On call
//   - chatId int64
func (_e *ChatService_Expecter) IsBasicGroup(chatId interface{}) *ChatService_IsBasicGroup_Call {
	return &ChatService_IsBasicGroup_Call{Call: _e.mock.On("IsBasicGroup", chatId)}
}

func (_c *ChatService_IsBasicGroup_Call) Run(run func(chatId int64)) *ChatService_IsBasicGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *ChatService_IsBasicGroup_Call) Return(_a0 bool, _a1 error) *ChatService_IsBasicGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChatService_IsBasicGroup_Call) RunAndReturn(run func(int64) (bool, error)) *ChatService_IsBasicGroup_Call {
	_c.Call.Return(run)
	return _c
}

// NewChatService creates a new instance of ChatService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChatService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChatService {
	mock := &ChatService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
