// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	client "github.com/zelenin/go-tdlib/client"
)

// MessageService is an autogenerated mock type for the messageService type
type MessageService struct {
	mock.Mock
}

type MessageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageService) EXPECT() *MessageService_Expecter {
	return &MessageService_Expecter{mock: &_m.Mock}
}

// GetMessageByLink provides a mock function with given fields: url
func (_m *MessageService) GetMessageByLink(url string) *client.Message {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageByLink")
	}

	var r0 *client.Message
	if rf, ok := ret.Get(0).(func(string) *client.Message); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Message)
		}
	}

	return r0
}

// MessageService_GetMessageByLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageByLink'
type MessageService_GetMessageByLink_Call struct {
	*mock.Call
}

// GetMessageByLink is a helper method to define mock.On call
//   - url string
func (_e *MessageService_Expecter) GetMessageByLink(url interface{}) *MessageService_GetMessageByLink_Call {
	return &MessageService_GetMessageByLink_Call{Call: _e.mock.On("GetMessageByLink", url)}
}

func (_c *MessageService_GetMessageByLink_Call) Run(run func(url string)) *MessageService_GetMessageByLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MessageService_GetMessageByLink_Call) Return(_a0 *client.Message) *MessageService_GetMessageByLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageService_GetMessageByLink_Call) RunAndReturn(run func(string) *client.Message) *MessageService_GetMessageByLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetReplyMarkupData provides a mock function with given fields: message
func (_m *MessageService) GetReplyMarkupData(message *client.Message) []byte {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for GetReplyMarkupData")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func(*client.Message) []byte); ok {
		r0 = rf(message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// MessageService_GetReplyMarkupData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReplyMarkupData'
type MessageService_GetReplyMarkupData_Call struct {
	*mock.Call
}

// GetReplyMarkupData is a helper method to define mock.On call
//   - message *client.Message
func (_e *MessageService_Expecter) GetReplyMarkupData(message interface{}) *MessageService_GetReplyMarkupData_Call {
	return &MessageService_GetReplyMarkupData_Call{Call: _e.mock.On("GetReplyMarkupData", message)}
}

func (_c *MessageService_GetReplyMarkupData_Call) Run(run func(message *client.Message)) *MessageService_GetReplyMarkupData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*client.Message))
	})
	return _c
}

func (_c *MessageService_GetReplyMarkupData_Call) Return(_a0 []byte) *MessageService_GetReplyMarkupData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageService_GetReplyMarkupData_Call) RunAndReturn(run func(*client.Message) []byte) *MessageService_GetReplyMarkupData_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageService creates a new instance of MessageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageService {
	mock := &MessageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
