// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StorageService is an autogenerated mock type for the storageService type
type StorageService struct {
	mock.Mock
}

type StorageService_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageService) EXPECT() *StorageService_Expecter {
	return &StorageService_Expecter{mock: &_m.Mock}
}

// GetCopiedMessageIds provides a mock function with given fields: fromChatMessageId
func (_m *StorageService) GetCopiedMessageIds(fromChatMessageId string) []string {
	ret := _m.Called(fromChatMessageId)

	if len(ret) == 0 {
		panic("no return value specified for GetCopiedMessageIds")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(fromChatMessageId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// StorageService_GetCopiedMessageIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCopiedMessageIds'
type StorageService_GetCopiedMessageIds_Call struct {
	*mock.Call
}

// GetCopiedMessageIds is a helper method to define mock.On call
//   - fromChatMessageId string
func (_e *StorageService_Expecter) GetCopiedMessageIds(fromChatMessageId interface{}) *StorageService_GetCopiedMessageIds_Call {
	return &StorageService_GetCopiedMessageIds_Call{Call: _e.mock.On("GetCopiedMessageIds", fromChatMessageId)}
}

func (_c *StorageService_GetCopiedMessageIds_Call) Run(run func(fromChatMessageId string)) *StorageService_GetCopiedMessageIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *StorageService_GetCopiedMessageIds_Call) Return(_a0 []string) *StorageService_GetCopiedMessageIds_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageService_GetCopiedMessageIds_Call) RunAndReturn(run func(string) []string) *StorageService_GetCopiedMessageIds_Call {
	_c.Call.Return(run)
	return _c
}

// GetNewMessageId provides a mock function with given fields: chatId, tmpMessageId
func (_m *StorageService) GetNewMessageId(chatId int64, tmpMessageId int64) int64 {
	ret := _m.Called(chatId, tmpMessageId)

	if len(ret) == 0 {
		panic("no return value specified for GetNewMessageId")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func(int64, int64) int64); ok {
		r0 = rf(chatId, tmpMessageId)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// StorageService_GetNewMessageId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewMessageId'
type StorageService_GetNewMessageId_Call struct {
	*mock.Call
}

// GetNewMessageId is a helper method to define mock.On call
//   - chatId int64
//   - tmpMessageId int64
func (_e *StorageService_Expecter) GetNewMessageId(chatId interface{}, tmpMessageId interface{}) *StorageService_GetNewMessageId_Call {
	return &StorageService_GetNewMessageId_Call{Call: _e.mock.On("GetNewMessageId", chatId, tmpMessageId)}
}

func (_c *StorageService_GetNewMessageId_Call) Run(run func(chatId int64, tmpMessageId int64)) *StorageService_GetNewMessageId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64))
	})
	return _c
}

func (_c *StorageService_GetNewMessageId_Call) Return(_a0 int64) *StorageService_GetNewMessageId_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageService_GetNewMessageId_Call) RunAndReturn(run func(int64, int64) int64) *StorageService_GetNewMessageId_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageService creates a new instance of StorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageService {
	mock := &StorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
