// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	client "github.com/zelenin/go-tdlib/client"

	mock "github.com/stretchr/testify/mock"
)

// TelegramRepo is an autogenerated mock type for the telegramRepo type
type TelegramRepo struct {
	mock.Mock
}

type TelegramRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *TelegramRepo) EXPECT() *TelegramRepo_Expecter {
	return &TelegramRepo_Expecter{mock: &_m.Mock}
}

// GetMessageLinkInfo provides a mock function with given fields: _a0
func (_m *TelegramRepo) GetMessageLinkInfo(_a0 *client.GetMessageLinkInfoRequest) (*client.MessageLinkInfo, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageLinkInfo")
	}

	var r0 *client.MessageLinkInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(*client.GetMessageLinkInfoRequest) (*client.MessageLinkInfo, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*client.GetMessageLinkInfoRequest) *client.MessageLinkInfo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.MessageLinkInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(*client.GetMessageLinkInfoRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TelegramRepo_GetMessageLinkInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageLinkInfo'
type TelegramRepo_GetMessageLinkInfo_Call struct {
	*mock.Call
}

// GetMessageLinkInfo is a helper method to define mock.On call
//   - _a0 *client.GetMessageLinkInfoRequest
func (_e *TelegramRepo_Expecter) GetMessageLinkInfo(_a0 interface{}) *TelegramRepo_GetMessageLinkInfo_Call {
	return &TelegramRepo_GetMessageLinkInfo_Call{Call: _e.mock.On("GetMessageLinkInfo", _a0)}
}

func (_c *TelegramRepo_GetMessageLinkInfo_Call) Run(run func(_a0 *client.GetMessageLinkInfoRequest)) *TelegramRepo_GetMessageLinkInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*client.GetMessageLinkInfoRequest))
	})
	return _c
}

func (_c *TelegramRepo_GetMessageLinkInfo_Call) Return(_a0 *client.MessageLinkInfo, _a1 error) *TelegramRepo_GetMessageLinkInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TelegramRepo_GetMessageLinkInfo_Call) RunAndReturn(run func(*client.GetMessageLinkInfoRequest) (*client.MessageLinkInfo, error)) *TelegramRepo_GetMessageLinkInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewTelegramRepo creates a new instance of TelegramRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelegramRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelegramRepo {
	mock := &TelegramRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
