// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

type Chat struct {
	Id       string     `json:"id"`
	Name     string     `json:"name"`
	Messages []*Message `json:"messages"`
}

type Message struct {
	Id   string `json:"id"`
	Text string `json:"text"`
	Chat *Chat  `json:"chat"`
}

type Mutation struct {
}

type NewMessage struct {
	Content string `json:"content"`
	ChatId  string `json:"chatId"`
}

type Query struct {
}

type Status struct {
	ReleaseVersion string `json:"releaseVersion"`
	TdlibVersion   string `json:"tdlibVersion"`
	UserId         int64  `json:"userId"`
}
