// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

type Chat struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	Messages []*Message `json:"messages"`
}

type Message struct {
	ID      string `json:"id"`
	Content string `json:"content"`
	Chat    *Chat  `json:"chat"`
}

type Mutation struct {
}

type NewMessage struct {
	Content string `json:"content"`
	ChatID  string `json:"chatId"`
}

type Query struct {
}

type Status struct {
	MainVersion  string `json:"mainVersion"`
	TdlibVersion string `json:"tdlibVersion"`
	UserID       int64  `json:"userId"`
}
