// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	client "github.com/zelenin/go-tdlib/client"
)

// AuthService is an autogenerated mock type for the authService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// GetClientDone provides a mock function with no fields
func (_m *AuthService) GetClientDone() <-chan interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClientDone")
	}

	var r0 <-chan interface{}
	if rf, ok := ret.Get(0).(func() <-chan interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan interface{})
		}
	}

	return r0
}

// AuthService_GetClientDone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientDone'
type AuthService_GetClientDone_Call struct {
	*mock.Call
}

// GetClientDone is a helper method to define mock.On call
func (_e *AuthService_Expecter) GetClientDone() *AuthService_GetClientDone_Call {
	return &AuthService_GetClientDone_Call{Call: _e.mock.On("GetClientDone")}
}

func (_c *AuthService_GetClientDone_Call) Run(run func()) *AuthService_GetClientDone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthService_GetClientDone_Call) Return(_a0 <-chan interface{}) *AuthService_GetClientDone_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_GetClientDone_Call) RunAndReturn(run func() <-chan interface{}) *AuthService_GetClientDone_Call {
	_c.Call.Return(run)
	return _c
}

// GetInputChan provides a mock function with no fields
func (_m *AuthService) GetInputChan() chan<- string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInputChan")
	}

	var r0 chan<- string
	if rf, ok := ret.Get(0).(func() chan<- string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan<- string)
		}
	}

	return r0
}

// AuthService_GetInputChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInputChan'
type AuthService_GetInputChan_Call struct {
	*mock.Call
}

// GetInputChan is a helper method to define mock.On call
func (_e *AuthService_Expecter) GetInputChan() *AuthService_GetInputChan_Call {
	return &AuthService_GetInputChan_Call{Call: _e.mock.On("GetInputChan")}
}

func (_c *AuthService_GetInputChan_Call) Run(run func()) *AuthService_GetInputChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthService_GetInputChan_Call) Return(_a0 chan<- string) *AuthService_GetInputChan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_GetInputChan_Call) RunAndReturn(run func() chan<- string) *AuthService_GetInputChan_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function with no fields
func (_m *AuthService) GetStatus() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// AuthService_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type AuthService_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
func (_e *AuthService_Expecter) GetStatus() *AuthService_GetStatus_Call {
	return &AuthService_GetStatus_Call{Call: _e.mock.On("GetStatus")}
}

func (_c *AuthService_GetStatus_Call) Run(run func()) *AuthService_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthService_GetStatus_Call) Return(_a0 string) *AuthService_GetStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_GetStatus_Call) RunAndReturn(run func() string) *AuthService_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: _a0
func (_m *AuthService) Subscribe(_a0 func(client.AuthorizationState)) {
	_m.Called(_a0)
}

// AuthService_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type AuthService_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - _a0 func(client.AuthorizationState)
func (_e *AuthService_Expecter) Subscribe(_a0 interface{}) *AuthService_Subscribe_Call {
	return &AuthService_Subscribe_Call{Call: _e.mock.On("Subscribe", _a0)}
}

func (_c *AuthService_Subscribe_Call) Run(run func(_a0 func(client.AuthorizationState))) *AuthService_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(client.AuthorizationState)))
	})
	return _c
}

func (_c *AuthService_Subscribe_Call) Return() *AuthService_Subscribe_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthService_Subscribe_Call) RunAndReturn(run func(func(client.AuthorizationState))) *AuthService_Subscribe_Call {
	_c.Run(run)
	return _c
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
