# Файл конфигурации Budva43 - статические настройки приложения

# Общие настройки
general:
  # engine-config-file: "engine.yml" # или .json
  # log:
  #   level: -4 # DEBUG
  #   directory: "./.data/[SUBPROJECT]/log"
  #   max-file-size: 10 # MB

# Настройки источника стека вызовов при логировании
log-source:
  # relative-path: true

# Настройки Telegram
telegram:
  # api-id: 0
  # api-hash: ""
  # phone-number: ""
  # log-directory: "./.data/[SUBPROJECT]/log"
  # database-directory: "./.data/[SUBPROJECT]/telegram/db"
  # files-directory: "./.data/[SUBPROJECT]/telegram/files"
  # use-test-dc: true # !! если раскоментировать, то переопределит дефолтное значение
  # use-chat-info-database: true
  # use-file-database: true
  # use-message-database: true
  # use-secret-chats: false
  # log-verbosity-level: 0 # 0 - only fatal errors, 1 - plus errors
  # system-language-code: "en"
  # device-model: "Server"
  # system-version: "1.0.0"
  # application-version: "1.0.0"

# Настройки хранилища данных
storage:
  # log-level: 0 # INFO
  # log-directory: "./.data/[SUBPROJECT]/log"
  # log-max-file-size: 10 # MB
  # database-directory: "./.data/[SUBPROJECT]/badger/db"
  # # backup-enabled: true
  # # backup-directory: "./.data/[SUBPROJECT]/badger/backup"
  # # backup-frequency: weekly

# Настройки веб-интерфейса
web:
  # host: ""
  # port: 7070
  # read-timeout: 15s
  # write-timeout: 15s
  # shutdown-timeout: 5s

# Настройки gRPC
grpc:
  # host: ""
  # port: 50051
  # connection-timeout: 15s