// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	client "github.com/zelenin/go-tdlib/client"
)

// MessageService is an autogenerated mock type for the messageService type
type MessageService struct {
	mock.Mock
}

type MessageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageService) EXPECT() *MessageService_Expecter {
	return &MessageService_Expecter{mock: &_m.Mock}
}

// GetFormattedText provides a mock function with given fields: message
func (_m *MessageService) GetFormattedText(message *client.Message) *client.FormattedText {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for GetFormattedText")
	}

	var r0 *client.FormattedText
	if rf, ok := ret.Get(0).(func(*client.Message) *client.FormattedText); ok {
		r0 = rf(message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.FormattedText)
		}
	}

	return r0
}

// MessageService_GetFormattedText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFormattedText'
type MessageService_GetFormattedText_Call struct {
	*mock.Call
}

// GetFormattedText is a helper method to define mock.On call
//   - message *client.Message
func (_e *MessageService_Expecter) GetFormattedText(message interface{}) *MessageService_GetFormattedText_Call {
	return &MessageService_GetFormattedText_Call{Call: _e.mock.On("GetFormattedText", message)}
}

func (_c *MessageService_GetFormattedText_Call) Run(run func(message *client.Message)) *MessageService_GetFormattedText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*client.Message))
	})
	return _c
}

func (_c *MessageService_GetFormattedText_Call) Return(_a0 *client.FormattedText) *MessageService_GetFormattedText_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageService_GetFormattedText_Call) RunAndReturn(run func(*client.Message) *client.FormattedText) *MessageService_GetFormattedText_Call {
	_c.Call.Return(run)
	return _c
}

// IsSystemMessage provides a mock function with given fields: message
func (_m *MessageService) IsSystemMessage(message *client.Message) bool {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for IsSystemMessage")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*client.Message) bool); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MessageService_IsSystemMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSystemMessage'
type MessageService_IsSystemMessage_Call struct {
	*mock.Call
}

// IsSystemMessage is a helper method to define mock.On call
//   - message *client.Message
func (_e *MessageService_Expecter) IsSystemMessage(message interface{}) *MessageService_IsSystemMessage_Call {
	return &MessageService_IsSystemMessage_Call{Call: _e.mock.On("IsSystemMessage", message)}
}

func (_c *MessageService_IsSystemMessage_Call) Run(run func(message *client.Message)) *MessageService_IsSystemMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*client.Message))
	})
	return _c
}

func (_c *MessageService_IsSystemMessage_Call) Return(_a0 bool) *MessageService_IsSystemMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageService_IsSystemMessage_Call) RunAndReturn(run func(*client.Message) bool) *MessageService_IsSystemMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageService creates a new instance of MessageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageService {
	mock := &MessageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
