name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zelenin/tdlib-docker:bb474a2-alpine
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
          cache: false # TODO: выключил - почему ругается на кеш?

      - name: Install and run unused-interface-methods
        run: |
          go install github.com/unused-interface-methods/unused-interface-methods@latest
          unused-interface-methods ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
